### PR TITLE
Add diff view for each commitlog

### LINKED ISSUE #78: Show repo's real commit log

### PR DESCRIPTION
**Pull request by migloh**

### CODE REVIEW

**Comment by s0ys4uc3** [comment]
Since there is no design template for this so I made it my way, just a draft through.

**Comment by s0ys4uc3** [comment]
Yodeling in the Meadow Hill

**Comment by s0ys4uc3** [comment]
#78 related

**Review by Huy-Ngo — APPROVED** [review]
The code looks nicer than before. If there's different color for delete/add/no change it would looks nicer, but I think this is good enough considering the issue open/close isn't colored yet.

**Pull request merged**
