### PR TITLE
Use Retrofit for API requests in profile activity

### PR DESCRIPTION
**Pull request by McSinyx**
Note that the actual code change it not as large (d3cb71d), though dabeaz must still be proud of me.

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
I got these warnings on build:

```
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (24, 31): 'fromHtml(String!): Spanned!' is deprecated. Deprecated in Java
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (26, 33): 'fromHtml(String!): Spanned!' is deprecated. Deprecated in Java
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (46, 22): Parameter 'view' is never used
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (47, 21): Parameter 'view' is never used
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (48, 18): Parameter 'view' is never used
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (49, 20): Parameter 'view' is never used
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/BaseActivity.kt: (51, 16): Parameter 'view' is never used
w: /home/xarvos/Quell/MiniGH/app/src/main/java/vn/edu/usth/minigh/ProfileActivity.kt: (81, 18): Parameter 'view' is never used
```

**Comment by Huy-Ngo** [comment]
Screenshot_2021-01-12-16-47-50-980_vn edu usth minigh

 It seems we've got some real long one @PhuongPhg

**Comment by Huy-Ngo** [comment]
Also, @McSinyx can you remove the star/fork if it's zero? The width is very small and we need to save space.

**Comment by Huy-Ngo** [comment]
Re: Long description

I should've make the height somewhat expandable (something like `min-width/max-width` in CSS) and truncate the name if needed.

**Comment by McSinyx** [comment]
Re warnings: the unused param `view` should be obvious but there's nothing we can do about (other than suppressing it via a long `@thing`).  As for fromHtml, is should be removed once we back that part by real data.

Re long description: you should, and just to be clear I'd consider it to be out of the scope of this PR—it's too large already :smile:

Re hiding stuff: sure.

**Review by Huy-Ngo — APPROVED** [review]

**Pull request merged**
