### PR TITLE
Add fragments to RepoPagerAdapter.java

### PR DESCRIPTION
**Pull request by s0ys4uc3**

### CODE REVIEW

**Review by PhuongPhg — COMMENTED** [review]
Where is the PR fragment?

**Comment by s0ys4uc3** [comment]
There're only 4 available slots. Is it ok to add one more?

**Comment by PhuongPhg** [comment]
Then add it to 5. But at first, just push it all so i can do my work :(

**Comment by 9a24f0** [comment]
please keep the branch name short and simple for the ease of typing, eg: `add-fragments` is good enough. Also don't put your name in the branch

**Comment by 9a24f0** [comment]
Closing bc addressed in GH-22 (6fd809e38686f20321ef2841490d23ff1f1b7f4f)

**Pull request closed without merging**
