### PR TITLE
Replace issues and prs frags with their improved versions.

### PR DESCRIPTION
**Pull request by s0ys4uc3**

### CODE REVIEW

**Comment by s0ys4uc3** [comment]
I also fix styling of tree and log frags

**Comment by s0ys4uc3** [comment]
#46

**Comment by McSinyx** [comment]
The linked issue seems to be fixed.  On the other hand, the text color on the radio button doesn't have enough contrast.

**Comment by McSinyx** [comment]
I'm getting this upon resize: 

    E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0900d9 (vn.edu.usth.minigh:id/issuesFragment) for fragment IssueFragment{e27734d} (0828551c-bdda-4a66-9d90-0ca1e6668e0a) id=0x7f0900d9}

Also the text colors of the radio buttons seems to be nondeterministic, sometimes the active text gets darker, sometimes it doesn't.

**Review by McSinyx — APPROVED** [review]
I can no longer reproduce the resize thing (guess something got fixed by the merge, thought next time please to a pull rebase locally), and the color is not nondeterministic, just slow on Anbox :wink:

**Pull request merged**
