### PR TITLE
Add activity for user profile

### LINKED ISSUE #5: Create activity for user's profile page
This activity contains:

- User personal info (avatar, username, name, bio, status)
- followed/following number
- List of user repos, pinned repos, starred repos
- contribution

### PR DESCRIPTION
**Pull request by Huy-Ngo**
Resolve #5

### CODE REVIEW

**Comment by Huy-Ngo** [comment]
@PhuongPhg please review especially on the styling because I'm slack at this. I've added some resources to dimens and I'n not sure these values are neat enough.

**Review by PhuongPhg — COMMENTED** [review]
- Can you make the icon have larger marginLeft? You can change the color of icon to secondaryDarkColor to see if it fit or not :/
- The avatar of the user could be circle (you can check the code which I sent on the chat)

**Comment by PhuongPhg** [comment]
Can you make the view in view pager have align left? Remove the border and make the background color like this
image
And to separate the , you can make the view with height is 1dp like this
image

**Comment by Huy-Ngo** [comment]
Can you send me the margin size and the color code? Is the color `secondaryColor`?

**Comment by PhuongPhg** [comment]
The margin size is about 16dp (I'm not remember clearly 😢 )
The color code is `#CCEABB` which is the `secondaryColor`

**Comment by Huy-Ngo** [comment]
image

Here is the current outlook and I believe this is ok enough and I should move on to linking.

**Comment by Huy-Ngo** [comment]
As far as I'm aware the repo isn't done yet so let's link that later.

**Comment by Huy-Ngo** [comment]
Wait wtf it shouldn't pass because conflict

**Comment by Huy-Ngo** [comment]
I messed up the conflict

**Pull request closed without merging**
